services:
  lldap:
    container_name: lldap
    image: lldap/lldap:stable
    ports:
      # For LDAP
      #- "3890:3890"
      # For LDAPS (LDAP Over SSL), enable port if LLDAP_LDAPS_OPTIONS__ENABLED set true, look env below
      #- "6360:6360"
      # For the web front-end
      #- "17170:17170"
    volumes:
      - ./appdata:/data
    env_file: .env
    restart: unless-stopped
    networks:
      - dmz
      - ldap
    labels:
      # Caddy
      caddy: "*.{$$INT_DOMAIN}"
      caddy.1_@lldap: "host lldap.{$$INT_DOMAIN}"
      caddy.1_handle: "@lldap"
      caddy.1_handle.reverse_proxy: "{{upstreams 17170}}"
      # Diun
      diun.enable: true

networks:
  dmz:
    external: true
  ldap:
    external: true
